Clears error when Railties is loaded but not (completely?) required
$ rake standard
rake aborted!
NameError: uninitialized constant Standard::Rails::Railtie
/Users/justin/code/standardrb/standard/lib/standard/railtie.rb:4:in `<module:Standard>'
/Users/justin/code/standardrb/standard/lib/standard/railtie.rb:3:in `<main>'
<internal:/Users/justin/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/justin/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/justin/code/standardrb/standard/lib/standard.rb:11:in `<main>'
<internal:/Users/justin/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/justin/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/justin/code/standardrb/standard/lib/standard/rake.rb:16:in `block in <main>'